# Generated by Django 5.0 on 2026-03-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
