# Generated by Django 5.0 on 2026-03-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Tteacher')], default='student', max_length=20),
        ),
    ]
