# Generated by Django 5.0 on 2026-03-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ST', 'Freshman'), ('TE', 'Sophomore')], default='ST', max_length=2),
        ),
    ]
